import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";
import { readFile, writeFile } from "node:fs/promises";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: {
		main: "src/main.ts",
		api: "src/api.ts",
	},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	minify: prod,
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: ".",
	entryNames: "[name]",
	loader: {
	   ".png": "base64",
	   ".svg": "base64",
	},
	plugins: [
		inlineWorkerPlugin({
			// Extra esbuild options for worker bundles
			format: "iife",
			target: "es2022",
			treeShaking: true,
			minify: prod,
			// Externalize Node.js builtins - sql.js conditionally requires them but won't use them in browser
			external: [...builtinModules],
			// Define stubs for Node.js globals that sql.js checks
			define: {
				'global': 'self',
			},
		}),
	],
});

if (prod) {
	await context.rebuild();
	const cssPath = "main.css";
	const css = await readFile(cssPath, "utf8");
	const expandedHex = css
		.replace(/#([0-9a-f])([0-9a-f])([0-9a-f])([0-9a-f])(?=[^0-9a-f]|$)/gi,
			(_match, r, g, b, a) => `#${r}${r}${g}${g}${b}${b}${a}${a}`)
		.replace(/#([0-9a-f])([0-9a-f])([0-9a-f])(?=[^0-9a-f]|$)/gi,
			(_match, r, g, b) => `#${r}${r}${g}${g}${b}${b}`);
	await writeFile(cssPath, expandedHex);
	process.exit(0);
} else {
	await context.watch();
}
