/**
 * VaultQuery public API types for third-party plugin integration.
 * GENERATED by scripts/generate-api-dts.mjs (npm run generate) - do not edit.
 *
 * Usage:
 *   npm install --save-dev github:bobstanton/vaultquery
 *
 *   import type { IVaultQueryAPI, QueryResult, PreviewResult } from 'vaultquery/api';
 */

export * from './api';
