// Generated by md-to-obsidian-dom
// Source: examples-views.md

import './styles.generated.css';

import type { RenderContext } from './types.generated';

export const pageId = "examples-views";
export const pageTitle = "Custom View Examples";

export const meta = {
  id: "examples-views",
  title: "Custom View Examples",
};

export const dynamicKeys: string[] = [];
export const linkedPages: string[] = [];

/**
 * Render the "Custom View Examples" help page
 * @param container - Container element to render into
 * @param _ctx - Render context with code highlighting and dynamic content handlers
 */
export function render(container: HTMLElement, _ctx: RenderContext): void {
  container.createEl('h1', { cls: 'vaultquery-help-heading vaultquery-help-h1', text: "Custom View Examples" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Recent activity" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Recently modified notes" });
  const codeBlock = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code = codeBlock.createEl('code');
  renderPrismCode(code, "CREATE VIEW recent_notes AS\nSELECT\n  path,\n  title,\n  datetime(modified/1000, 'unixepoch', 'localtime') as modified_at,\n  size\nFROM notes\nORDER BY modified DESC\nLIMIT 50", "vaultquery-view");
  codeBlock.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  const codeBlock1 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock1.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery\n" });
  const code1 = codeBlock1.createEl('code');
  renderPrismCode(code1, "SELECT * FROM recent_notes WHERE title LIKE '%project%'", "vaultquery");
  codeBlock1.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Recently created notes" });
  const codeBlock2 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock2.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code2 = codeBlock2.createEl('code');
  renderPrismCode(code2, "CREATE VIEW new_notes AS\nSELECT\n  path,\n  title,\n  datetime(created/1000, 'unixepoch', 'localtime') as created_at\nFROM notes\nWHERE created > (strftime('%s', 'now', '-7 days') * 1000)\nORDER BY created DESC", "vaultquery-view");
  codeBlock2.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Task management" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Open tasks with context" });
  const codeBlock3 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock3.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code3 = codeBlock3.createEl('code');
  renderPrismCode(code3, "CREATE VIEW open_tasks AS\nSELECT\n  t.path,\n  t.task_text,\n  t.priority,\n  t.due_date,\n  t.tags,\n  t.section_heading,\n  CASE\n    WHEN t.due_date < date('now') THEN 'overdue'\n    WHEN t.due_date = date('now') THEN 'today'\n    WHEN t.due_date <= date('now', '+7 days') THEN 'this_week'\n    ELSE 'later'\n  END as urgency\nFROM tasks t\nWHERE t.status = 'TODO'", "vaultquery-view");
  codeBlock3.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  const codeBlock4 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock4.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery\n" });
  const code4 = codeBlock4.createEl('code');
  renderPrismCode(code4, "SELECT * FROM open_tasks\nWHERE urgency IN ('overdue', 'today')\nORDER BY due_date", "vaultquery");
  codeBlock4.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Tasks by project" });
  const codeBlock5 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock5.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code5 = codeBlock5.createEl('code');
  renderPrismCode(code5, "CREATE VIEW project_tasks AS\nSELECT\n  path_parent(t.path) as project,\n  t.status,\n  COUNT(*) as task_count\nFROM tasks t\nGROUP BY path_parent(t.path), t.status", "vaultquery-view");
  codeBlock5.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  const codeBlock6 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock6.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery\n" });
  const code6 = codeBlock6.createEl('code');
  renderPrismCode(code6, "SELECT\n  project,\n  SUM(CASE WHEN status = 'DONE' THEN task_count ELSE 0 END) as done,\n  SUM(CASE WHEN status = 'TODO' THEN task_count ELSE 0 END) as todo\nFROM project_tasks\nGROUP BY project\nORDER BY todo DESC", "vaultquery");
  codeBlock6.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Overdue tasks" });
  const codeBlock7 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock7.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code7 = codeBlock7.createEl('code');
  renderPrismCode(code7, "CREATE VIEW overdue_tasks AS\nSELECT\n  path,\n  task_text,\n  due_date,\n  julianday('now') - julianday(due_date) as days_overdue\nFROM tasks\nWHERE status = 'TODO'\n  AND due_date IS NOT NULL\n  AND due_date < date('now')\nORDER BY due_date", "vaultquery-view");
  codeBlock7.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Note organization" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Orphan notes (no incoming links)" });
  const codeBlock8 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock8.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code8 = codeBlock8.createEl('code');
  renderPrismCode(code8, "CREATE VIEW orphan_notes AS\nSELECT n.path, n.title, n.modified\nFROM notes n\nLEFT JOIN links l ON n.path = l.link_target_path\nWHERE l.link_target_path IS NULL\n  AND n.path NOT LIKE '%/_templates/%'\n  AND n.path NOT LIKE '%.excalidraw.md'\nORDER BY n.modified DESC", "vaultquery-view");
  codeBlock8.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Notes by folder" });
  const codeBlock9 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock9.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code9 = codeBlock9.createEl('code');
  renderPrismCode(code9, "CREATE VIEW folder_stats AS\nSELECT\n  path_parent(path) as folder,\n  COUNT(*) as note_count,\n  SUM(size) as total_size,\n  MAX(modified) as last_modified\nFROM notes\nGROUP BY path_parent(path)\nORDER BY note_count DESC", "vaultquery-view");
  codeBlock9.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Large notes" });
  const codeBlock10 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock10.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code10 = codeBlock10.createEl('code');
  renderPrismCode(code10, "CREATE VIEW large_notes AS\nSELECT\n  path,\n  title,\n  size,\n  round(size / 1024.0, 1) as size_kb\nFROM notes\nWHERE size > 10000\nORDER BY size DESC", "vaultquery-view");
  codeBlock10.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Tag analysis" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Tag usage statistics" });
  const codeBlock11 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock11.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code11 = codeBlock11.createEl('code');
  renderPrismCode(code11, "CREATE VIEW tag_stats AS\nSELECT\n  tag_name,\n  COUNT(*) as usage_count,\n  COUNT(DISTINCT path) as note_count\nFROM tags\nGROUP BY tag_name\nORDER BY usage_count DESC", "vaultquery-view");
  codeBlock11.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  const codeBlock12 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock12.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery\n" });
  const code12 = codeBlock12.createEl('code');
  renderPrismCode(code12, "SELECT * FROM tag_stats WHERE usage_count > 5", "vaultquery");
  codeBlock12.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Notes with multiple tags" });
  const codeBlock13 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock13.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code13 = codeBlock13.createEl('code');
  renderPrismCode(code13, "CREATE VIEW multi_tag_notes AS\nSELECT\n  path,\n  COUNT(*) as tag_count,\n  GROUP_CONCAT(tag_name, ', ') as all_tags\nFROM tags\nGROUP BY path\nHAVING COUNT(*) > 3\nORDER BY tag_count DESC", "vaultquery-view");
  codeBlock13.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Link analysis" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Most linked notes" });
  const codeBlock14 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock14.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code14 = codeBlock14.createEl('code');
  renderPrismCode(code14, "CREATE VIEW popular_notes AS\nSELECT\n  link_target_path as path,\n  COUNT(*) as incoming_links\nFROM links\nWHERE link_target_path IS NOT NULL\nGROUP BY link_target_path\nORDER BY incoming_links DESC", "vaultquery-view");
  codeBlock14.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Broken links" });
  const para = container.createEl('p', { cls: 'vaultquery-help-paragraph' });
  para.appendText("Using the ");
  para.createEl('code', { cls: 'vaultquery-help-code', text: "unresolved_links" });
  para.appendText(" table:");
  const codeBlock15 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock15.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code15 = codeBlock15.createEl('code');
  renderPrismCode(code15, "CREATE VIEW broken_links AS\nSELECT\n  path as source,\n  link_target as target,\n  link_count\nFROM unresolved_links", "vaultquery-view");
  codeBlock15.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Link graph edges" });
  const codeBlock16 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock16.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code16 = codeBlock16.createEl('code');
  renderPrismCode(code16, "CREATE VIEW link_graph AS\nSELECT DISTINCT\n  l.path as source,\n  l.link_target_path as target\nFROM links l\nJOIN notes n ON l.link_target_path = n.path\nWHERE l.link_type = 'internal'", "vaultquery-view");
  codeBlock16.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Content analysis" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Heading structure" });
  const codeBlock17 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock17.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code17 = codeBlock17.createEl('code');
  renderPrismCode(code17, "CREATE VIEW heading_outline AS\nSELECT\n  path,\n  level,\n  heading_text,\n  line_number,\n  SUBSTR('      ', 1, (level - 1) * 2) || heading_text as indented\nFROM headings\nORDER BY path, line_number", "vaultquery-view");
  codeBlock17.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  const codeBlock18 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock18.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery\n" });
  const code18 = codeBlock18.createEl('code');
  renderPrismCode(code18, "SELECT indented FROM heading_outline WHERE path = '{this.path}'", "vaultquery");
  codeBlock18.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Notes with properties" });
  const codeBlock19 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock19.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code19 = codeBlock19.createEl('code');
  renderPrismCode(code19, "CREATE VIEW notes_by_status AS\nSELECT\n  n.path,\n  n.title,\n  p.value as status\nFROM notes n\nJOIN properties p ON n.path = p.path\nWHERE p.key = 'status'\nORDER BY p.value, n.title", "vaultquery-view");
  codeBlock19.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Property value counts" });
  const codeBlock20 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock20.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code20 = codeBlock20.createEl('code');
  renderPrismCode(code20, "CREATE VIEW property_stats AS\nSELECT\n  key,\n  value,\n  COUNT(*) as count\nFROM properties\nWHERE key IN ('status', 'type', 'category', 'priority')\nGROUP BY key, value\nORDER BY key, count DESC", "vaultquery-view");
  codeBlock20.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Daily notes" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Daily notes summary" });
  const codeBlock21 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock21.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code21 = codeBlock21.createEl('code');
  renderPrismCode(code21, "CREATE VIEW daily_notes AS\nSELECT\n  path,\n  title,\n  SUBSTR(path_basename(path), 1, 10) as date,\n  size,\n  (SELECT COUNT(*) FROM tasks t WHERE t.path = n.path) as task_count\nFROM notes n\nWHERE path LIKE 'Daily/%'\n  OR path LIKE 'Journal/%'\nORDER BY date DESC", "vaultquery-view");
  codeBlock21.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Weekly summary" });
  const codeBlock22 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock22.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code22 = codeBlock22.createEl('code');
  renderPrismCode(code22, "CREATE VIEW weekly_summary AS\nSELECT\n  strftime('%Y-W%W', SUBSTR(path_basename(path), 1, 10)) as week,\n  COUNT(*) as entries,\n  SUM(size) as total_size\nFROM notes\nWHERE path LIKE 'Daily/%'\nGROUP BY week\nORDER BY week DESC", "vaultquery-view");
  codeBlock22.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Combining views" });
  const para1 = container.createEl('p', { cls: 'vaultquery-help-paragraph' });
  para1.appendText("Views can reference other views:");
  const codeBlock23 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock23.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-view\n" });
  const code23 = codeBlock23.createEl('code');
  renderPrismCode(code23, "CREATE VIEW high_priority_overdue AS\nSELECT *\nFROM overdue_tasks\nWHERE task_text LIKE '%#urgent%'\n   OR task_text LIKE '%!high%'\nORDER BY days_overdue DESC", "vaultquery-view");
  codeBlock23.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
}

type PrismTokenStream = string | PrismToken | PrismTokenStream[];

interface PrismToken {
  type: string;
  content: PrismTokenStream;
  alias?: string | string[];
}

interface PrismApi {
  languages: Record<string, unknown>;
  tokenize: (code: string, grammar: unknown) => PrismTokenStream[];
}

declare const Prism: PrismApi | undefined;

function renderPrismCode(container: HTMLElement, source: string, language: string): void {
  const prism = typeof Prism !== 'undefined' ? Prism : undefined;
  const grammar = prism?.languages[language];

  if (!prism || !grammar) {
    container.appendText(source);
    return;
  }

  appendPrismTokens(container, prism.tokenize(source, grammar));
}

function appendPrismTokens(container: HTMLElement, tokenStream: PrismTokenStream): void {
  if (typeof tokenStream === 'string') {
    container.appendText(tokenStream);
    return;
  }

  if (Array.isArray(tokenStream)) {
    for (const token of tokenStream) {
      appendPrismTokens(container, token);
    }
    return;
  }

  const aliases = Array.isArray(tokenStream.alias)
    ? tokenStream.alias
    : tokenStream.alias ? [tokenStream.alias] : [];
  const span = container.createSpan({ cls: ['token', tokenStream.type, ...aliases].join(' ') });
  appendPrismTokens(span, tokenStream.content);
}