// Generated by md-to-obsidian-dom
// Source: examples-functions.md

import './styles.generated.css';

import type { RenderContext } from './types.generated';

export const pageId = "examples-functions";
export const pageTitle = "Custom Function Examples";

export const meta = {
  id: "examples-functions",
  title: "Custom Function Examples",
};

export const dynamicKeys: string[] = [];
export const linkedPages: string[] = [];

/**
 * Render the "Custom Function Examples" help page
 * @param container - Container element to render into
 * @param _ctx - Render context with code highlighting and dynamic content handlers
 */
export function render(container: HTMLElement, _ctx: RenderContext): void {
  container.createEl('h1', { cls: 'vaultquery-help-heading vaultquery-help-h1', text: "Custom Function Examples" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Text formatting" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Capitalize first letter" });
  const codeBlock = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-function\n" });
  const code = codeBlock.createEl('code');
  renderPrismCode(code, "function capitalize(str) {\n  if (!str) return null;\n  return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();\n}", "vaultquery-function");
  codeBlock.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  const codeBlock1 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock1.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery\n" });
  const code1 = codeBlock1.createEl('code');
  renderPrismCode(code1, "SELECT capitalize(title) as formatted FROM notes LIMIT 5", "vaultquery");
  codeBlock1.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Title case" });
  const codeBlock2 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock2.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-function\n" });
  const code2 = codeBlock2.createEl('code');
  renderPrismCode(code2, "function title_case(str) {\n  if (!str) return null;\n  return str.replace(/\\w\\S*/g, txt =>\n    txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase()\n  );\n}", "vaultquery-function");
  codeBlock2.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Extract first word" });
  const codeBlock3 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock3.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-function\n" });
  const code3 = codeBlock3.createEl('code');
  renderPrismCode(code3, "function first_word(text) {\n  if (!text) return null;\n  const match = text.match(/^\\s*(\\S+)/);\n  return match ? match[1] : null;\n}", "vaultquery-function");
  codeBlock3.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Word count" });
  const codeBlock4 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock4.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-function\n" });
  const code4 = codeBlock4.createEl('code');
  renderPrismCode(code4, "function word_count(text) {\n  if (!text) return 0;\n  return text.trim().split(/\\s+/).filter(w => w.length > 0).length;\n}", "vaultquery-function");
  codeBlock4.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  const codeBlock5 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock5.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery\n" });
  const code5 = codeBlock5.createEl('code');
  renderPrismCode(code5, "SELECT title, word_count(content) as words\nFROM notes\nORDER BY word_count(content) DESC\nLIMIT 10", "vaultquery");
  codeBlock5.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Date calculations" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Days until date" });
  const codeBlock6 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock6.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-function\n" });
  const code6 = codeBlock6.createEl('code');
  renderPrismCode(code6, "function days_until(dateStr) {\n  if (!dateStr) return null;\n  const target = new Date(dateStr);\n  const today = new Date();\n  today.setHours(0, 0, 0, 0);\n  return Math.ceil((target - today) / (1000 * 60 * 60 * 24));\n}", "vaultquery-function");
  codeBlock6.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  const codeBlock7 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock7.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery\n" });
  const code7 = codeBlock7.createEl('code');
  renderPrismCode(code7, "SELECT task_text, due_date, days_until(due_date) as days_left\nFROM tasks\nWHERE due_date IS NOT NULL AND days_until(due_date) >= 0\nORDER BY days_until(due_date)", "vaultquery");
  codeBlock7.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Days since date" });
  const codeBlock8 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock8.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-function\n" });
  const code8 = codeBlock8.createEl('code');
  renderPrismCode(code8, "function days_since(dateStr) {\n  if (!dateStr) return null;\n  const past = new Date(dateStr);\n  const today = new Date();\n  today.setHours(0, 0, 0, 0);\n  return Math.floor((today - past) / (1000 * 60 * 60 * 24));\n}", "vaultquery-function");
  codeBlock8.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Week number" });
  const codeBlock9 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock9.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-function\n" });
  const code9 = codeBlock9.createEl('code');
  renderPrismCode(code9, "function week_number(dateStr) {\n  if (!dateStr) return null;\n  const date = new Date(dateStr);\n  const start = new Date(date.getFullYear(), 0, 1);\n  const days = Math.floor((date - start) / (1000 * 60 * 60 * 24));\n  return Math.ceil((days + start.getDay() + 1) / 7);\n}", "vaultquery-function");
  codeBlock9.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "JSON handling" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Get JSON property" });
  const codeBlock10 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock10.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-function\n" });
  const code10 = codeBlock10.createEl('code');
  renderPrismCode(code10, "function json_get(jsonStr, key) {\n  if (!jsonStr || !key) return null;\n  try {\n    const obj = JSON.parse(jsonStr);\n    return obj[key] ?? null;\n  } catch {\n    return null;\n  }\n}", "vaultquery-function");
  codeBlock10.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Get nested JSON property" });
  const codeBlock11 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock11.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-function\n" });
  const code11 = codeBlock11.createEl('code');
  renderPrismCode(code11, "function json_path(jsonStr, path) {\n  if (!jsonStr || !path) return null;\n  try {\n    const obj = JSON.parse(jsonStr);\n    return path.split('.').reduce((o, k) => o?.[k], obj) ?? null;\n  } catch {\n    return null;\n  }\n}", "vaultquery-function");
  codeBlock11.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  const codeBlock12 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock12.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery\n" });
  const code12 = codeBlock12.createEl('code');
  renderPrismCode(code12, "-- Example: json_path('{\"user\":{\"name\":\"Bob\"}}', 'user.name') returns 'Bob'\nSELECT json_path(row_json, 'Status') as status\nFROM table_rows\nWHERE json_path(row_json, 'Status') = 'Active'", "vaultquery");
  codeBlock12.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Tag and metadata" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Extract priority from text" });
  const codeBlock13 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock13.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-function\n" });
  const code13 = codeBlock13.createEl('code');
  renderPrismCode(code13, "function extract_priority(text) {\n  if (!text) return null;\n  const match = text.match(/[!@#]\\s*(high|medium|low|urgent)/i);\n  return match ? match[1].toLowerCase() : null;\n}", "vaultquery-function");
  codeBlock13.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Has hashtag" });
  const codeBlock14 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock14.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-function\n" });
  const code14 = codeBlock14.createEl('code');
  renderPrismCode(code14, "function has_tag(text, tag) {\n  if (!text || !tag) return 0;\n  const pattern = new RegExp('#' + tag + '\\\\b', 'i');\n  return pattern.test(text) ? 1 : 0;\n}", "vaultquery-function");
  codeBlock14.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  const codeBlock15 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock15.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery\n" });
  const code15 = codeBlock15.createEl('code');
  renderPrismCode(code15, "SELECT title, path\nFROM notes\nWHERE has_tag(content, 'important') = 1", "vaultquery");
  codeBlock15.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Extract all hashtags" });
  const codeBlock16 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock16.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-function\n" });
  const code16 = codeBlock16.createEl('code');
  renderPrismCode(code16, "function extract_tags(text) {\n  if (!text) return null;\n  const tags = text.match(/#[\\w-]+/g);\n  return tags ? tags.join(' ') : null;\n}", "vaultquery-function");
  codeBlock16.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Numeric utilities" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Clamp value" });
  const codeBlock17 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock17.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-function\n" });
  const code17 = codeBlock17.createEl('code');
  renderPrismCode(code17, "function clamp(value, min, max) {\n  if (value === null) return null;\n  return Math.min(Math.max(value, min), max);\n}", "vaultquery-function");
  codeBlock17.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Round to decimal places" });
  const codeBlock18 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock18.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-function\n" });
  const code18 = codeBlock18.createEl('code');
  renderPrismCode(code18, "function round_to(value, decimals) {\n  if (value === null) return null;\n  const factor = Math.pow(10, decimals || 0);\n  return Math.round(value * factor) / factor;\n}", "vaultquery-function");
  codeBlock18.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Percentage" });
  const codeBlock19 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock19.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-function\n" });
  const code19 = codeBlock19.createEl('code');
  renderPrismCode(code19, "function percentage(part, total) {\n  if (part === null || total === null || total === 0) return null;\n  return Math.round((part / total) * 100);\n}", "vaultquery-function");
  codeBlock19.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  const codeBlock20 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock20.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery\n" });
  const code20 = codeBlock20.createEl('code');
  renderPrismCode(code20, "SELECT\n  status,\n  COUNT(*) as count,\n  percentage(COUNT(*), (SELECT COUNT(*) FROM tasks)) || '%' as pct\nFROM tasks\nGROUP BY status", "vaultquery");
  codeBlock20.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "String utilities" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Truncate with ellipsis" });
  const codeBlock21 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock21.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-function\n" });
  const code21 = codeBlock21.createEl('code');
  renderPrismCode(code21, "function truncate(text, maxLen) {\n  if (!text) return null;\n  if (text.length <= maxLen) return text;\n  return text.substring(0, maxLen - 3) + '...';\n}", "vaultquery-function");
  codeBlock21.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h3', { cls: 'vaultquery-help-heading vaultquery-help-h3', text: "Remove markdown" });
  const codeBlock22 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock22.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-function\n" });
  const code22 = codeBlock22.createEl('code');
  renderPrismCode(code22, "function strip_markdown(text) {\n  if (!text) return null;\n  return text\n    .replace(/\\*\\*(.+?)\\*\\*/g, '$1')\n    .replace(/\\*(.+?)\\*/g, '$1')\n    .replace(/\\[\\[(.+?)\\]\\]/g, '$1')\n    .replace(/\\[(.+?)\\]\\(.+?\\)/g, '$1')\n    .replace(/^#+\\s*/gm, '')\n    .replace(/^[-*]\\s*/gm, '');\n}", "vaultquery-function");
  codeBlock22.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
}

type PrismTokenStream = string | PrismToken | PrismTokenStream[];

interface PrismToken {
  type: string;
  content: PrismTokenStream;
  alias?: string | string[];
}

interface PrismApi {
  languages: Record<string, unknown>;
  tokenize: (code: string, grammar: unknown) => PrismTokenStream[];
}

declare const Prism: PrismApi | undefined;

function renderPrismCode(container: HTMLElement, source: string, language: string): void {
  const prism = typeof Prism !== 'undefined' ? Prism : undefined;
  const grammar = prism?.languages[language];

  if (!prism || !grammar) {
    container.appendText(source);
    return;
  }

  appendPrismTokens(container, prism.tokenize(source, grammar));
}

function appendPrismTokens(container: HTMLElement, tokenStream: PrismTokenStream): void {
  if (typeof tokenStream === 'string') {
    container.appendText(tokenStream);
    return;
  }

  if (Array.isArray(tokenStream)) {
    for (const token of tokenStream) {
      appendPrismTokens(container, token);
    }
    return;
  }

  const aliases = Array.isArray(tokenStream.alias)
    ? tokenStream.alias
    : tokenStream.alias ? [tokenStream.alias] : [];
  const span = container.createSpan({ cls: ['token', tokenStream.type, ...aliases].join(' ') });
  appendPrismTokens(span, tokenStream.content);
}