// Auto-generated by md-to-obsidian-dom

import './styles.generated.css';

export type { RenderContext } from './types.generated';

import * as api_guide from './api-guide.generated';
import * as examples_functions from './examples-functions.generated';
import * as examples_views from './examples-views.generated';
import * as vaultquery_function_help from './vaultquery-function-help.generated';
import * as vaultquery_help from './vaultquery-help.generated';

export const pages = {
  [api_guide.pageId]: api_guide,
  [examples_functions.pageId]: examples_functions,
  [examples_views.pageId]: examples_views,
  [vaultquery_function_help.pageId]: vaultquery_function_help,
  [vaultquery_help.pageId]: vaultquery_help,
};

export type PageId = keyof typeof pages;

export function getPage(id: PageId) {
  return pages[id];
}

export function getAllPageIds(): PageId[] {
  return Object.keys(pages) as PageId[];
}