// Auto-generated by md-to-obsidian-dom

import type { App, Component } from 'obsidian';

/** Context for rendering help pages */
export interface RenderContext {
  /** Obsidian App instance */
  app: App;
  /** Component for lifecycle management */
  component: Component;
  /** Render dynamic content by key */
  renderDynamic: (container: HTMLElement, key: string) => void;
  /** Set an icon on an element (for callout icons) */
  setIcon: (element: HTMLElement, iconId: string) => void;
}