// Auto-generated by md-to-obsidian-dom

/** Context for rendering help pages */
export interface RenderContext {
  /** Render a code block (``` fences) - plugin handles rendering */
  renderCode: (container: HTMLElement, language: string, code: string) => void;
  /** Render dynamic content by key */
  renderDynamic: (container: HTMLElement, key: string) => void;
  /** Set an icon on an element (for callout icons) */
  setIcon: (element: HTMLElement, iconId: string) => void;
}