// Generated by md-to-obsidian-dom
// Source: vaultquery-calendar-help.md
/* eslint-disable obsidianmd/ui/sentence-case -- Generated help content */

import './styles.generated.css';

import type { RenderContext } from './types.generated';

export const pageId = "vaultquery-calendar-help";
export const pageTitle = "VaultQuery Calendar Help";

export const meta = {
  id: "vaultquery-calendar-help",
  title: "VaultQuery Calendar Help",
};

export const dynamicKeys: string[] = [];
export const linkedPages: string[] = [];

/**
 * Render the "VaultQuery Calendar Help" help page
 * @param container - Container element to render into
 * @param _ctx - Render context with code highlighting and dynamic content handlers
 */
export function render(container: HTMLElement, _ctx: RenderContext): void {
  container.createEl('h1', { cls: 'vaultquery-help-heading vaultquery-help-h1', text: "Calendar output" });
  const para = container.createEl('p', { cls: 'vaultquery-help-paragraph' });
  para.appendText("Use ");
  para.createEl('code', { cls: 'vaultquery-help-code', text: "vaultquery-calendar" });
  para.appendText(" to render query results as calendars. Each result row becomes one calendar item. At minimum, the query must return a date column.");
  const para1 = container.createEl('p', { cls: 'vaultquery-help-paragraph' });
  para1.appendText("Calendar output uses ");
  para1.createEl('a', { cls: 'vaultquery-help-link vaultquery-help-external-link', text: "FullCalendar Standard", attr: { href: "https://fullcalendar.io/", target: '_blank', rel: 'noopener' } });
  para1.appendText(". It defaults to month view with weeks displayed Sunday through Saturday. The toolbar can switch between month, week, and day views.");
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Calendar result columns" });
  const tableWrapper = container.createEl('div', { cls: 'vaultquery-help-table-wrapper' });
  const table = tableWrapper.createEl('table', { cls: 'vaultquery-help-table' });
  const thead = table.createEl('thead');
  const row = thead.createEl('tr');
  row.createEl('th', { text: "Column" });
  row.createEl('th', { text: "Description" });
  const tbody = table.createEl('tbody');
  const row1 = tbody.createEl('tr');
  const td = row1.createEl('td');
  td.createEl('code', { cls: 'vaultquery-help-code', text: "date" });
  row1.createEl('td', { text: "Event start date. Required" });
  const row2 = tbody.createEl('tr');
  const td1 = row2.createEl('td');
  td1.createEl('code', { cls: 'vaultquery-help-code', text: "end_date" });
  row2.createEl('td', { text: "Optional inclusive date-only end date for multi-day spans" });
  const row3 = tbody.createEl('tr');
  const td2 = row3.createEl('td');
  td2.createEl('code', { cls: 'vaultquery-help-code', text: "title" });
  row3.createEl('td', { text: "Event title. Defaults to the date when omitted" });
  const row4 = tbody.createEl('tr');
  const td3 = row4.createEl('td');
  td3.createEl('code', { cls: 'vaultquery-help-code', text: "description" });
  row4.createEl('td', { text: "Optional tooltip/details text" });
  const row5 = tbody.createEl('tr');
  const td4 = row5.createEl('td');
  td4.createEl('code', { cls: 'vaultquery-help-code', text: "path" });
  row5.createEl('td', { text: "Optional note path. When present, clicking the event opens the note" });
  const row6 = tbody.createEl('tr');
  const td5 = row6.createEl('td');
  td5.createEl('code', { cls: 'vaultquery-help-code', text: "backgroundColor" });
  row6.createEl('td', { text: "Optional event background color" });
  const row7 = tbody.createEl('tr');
  const td6 = row7.createEl('td');
  td6.createEl('code', { cls: 'vaultquery-help-code', text: "borderColor" });
  row7.createEl('td', { text: "Optional event border color" });
  const row8 = tbody.createEl('tr');
  const td7 = row8.createEl('td');
  td7.createEl('code', { cls: 'vaultquery-help-code', text: "color" });
  row8.createEl('td', { text: "Optional event label color" });
  const row9 = tbody.createEl('tr');
  const td8 = row9.createEl('td');
  td8.createEl('code', { cls: 'vaultquery-help-code', text: "allDay" });
  const td9 = row9.createEl('td');
  td9.appendText("Optional boolean. Defaults to ");
  td9.createEl('code', { cls: 'vaultquery-help-code', text: "true" });
  const para2 = container.createEl('p', { cls: 'vaultquery-help-paragraph' });
  para2.appendText("Date values can be ISO dates (");
  para2.createEl('code', { cls: 'vaultquery-help-code', text: "YYYY-MM-DD" });
  para2.appendText("), ISO datetimes, parseable date strings, or Unix timestamps. VaultQuery preserves timed values when they include a time component. ");
  para2.createEl('code', { cls: 'vaultquery-help-code', text: "end_date" });
  para2.appendText(" is inclusive for date-only ranges, so ");
  para2.createEl('code', { cls: 'vaultquery-help-code', text: "date: 2026-04-21" });
  para2.appendText(" with ");
  para2.createEl('code', { cls: 'vaultquery-help-code', text: "end_date: 2026-04-24" });
  para2.appendText(" renders through April 24. If ");
  para2.createEl('code', { cls: 'vaultquery-help-code', text: "end_date" });
  para2.appendText(" is earlier than ");
  para2.createEl('code', { cls: 'vaultquery-help-code', text: "date" });
  para2.appendText(", VaultQuery swaps the range endpoints.");
  const para3 = container.createEl('p', { cls: 'vaultquery-help-paragraph' });
  para3.appendText("Return ");
  para3.createEl('code', { cls: 'vaultquery-help-code', text: "backgroundColor" });
  para3.appendText(", ");
  para3.createEl('code', { cls: 'vaultquery-help-code', text: "borderColor" });
  para3.appendText(", and ");
  para3.createEl('code', { cls: 'vaultquery-help-code', text: "color" });
  para3.appendText(" to match CSS-style naming for event background, border, and label colors. Alias SQL columns to those names when needed.");
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Calendar config options" });
  const tableWrapper1 = container.createEl('div', { cls: 'vaultquery-help-table-wrapper' });
  const table1 = tableWrapper1.createEl('table', { cls: 'vaultquery-help-table' });
  const thead1 = table1.createEl('thead');
  const row10 = thead1.createEl('tr');
  row10.createEl('th', { text: "Option" });
  row10.createEl('th', { text: "Description" });
  const tbody1 = table1.createEl('tbody');
  const row11 = tbody1.createEl('tr');
  const td10 = row11.createEl('td');
  td10.createEl('code', { cls: 'vaultquery-help-code', text: "initialView" });
  const td11 = row11.createEl('td');
  td11.appendText("FullCalendar initial view: ");
  td11.createEl('code', { cls: 'vaultquery-help-code', text: "dayGridMonth" });
  td11.appendText(" (default), ");
  td11.createEl('code', { cls: 'vaultquery-help-code', text: "timeGridWeek" });
  td11.appendText(", or ");
  td11.createEl('code', { cls: 'vaultquery-help-code', text: "timeGridDay" });
  td11.appendText(". Short aliases ");
  td11.createEl('code', { cls: 'vaultquery-help-code', text: "month" });
  td11.appendText(", ");
  td11.createEl('code', { cls: 'vaultquery-help-code', text: "week" });
  td11.appendText(", and ");
  td11.createEl('code', { cls: 'vaultquery-help-code', text: "day" });
  td11.appendText(" also work");
  const row12 = tbody1.createEl('tr');
  const td12 = row12.createEl('td');
  td12.createEl('code', { cls: 'vaultquery-help-code', text: "initialDate" });
  const td13 = row12.createEl('td');
  td13.appendText("Initial date to display, as ");
  td13.createEl('code', { cls: 'vaultquery-help-code', text: "YYYY-MM-DD" });
  td13.appendText(", ");
  td13.createEl('code', { cls: 'vaultquery-help-code', text: "first" });
  td13.appendText(", or ");
  td13.createEl('code', { cls: 'vaultquery-help-code', text: "last" });
  td13.appendText(". ");
  td13.createEl('code', { cls: 'vaultquery-help-code', text: "first" });
  td13.appendText(" uses the earliest event date; ");
  td13.createEl('code', { cls: 'vaultquery-help-code', text: "last" });
  td13.appendText(" uses the latest event date");
  const row13 = tbody1.createEl('tr');
  const td14 = row13.createEl('td');
  td14.createEl('code', { cls: 'vaultquery-help-code', text: "height" });
  const td15 = row13.createEl('td');
  td15.appendText("FullCalendar height for the whole calendar. Use ");
  td15.createEl('code', { cls: 'vaultquery-help-code', text: "auto" });
  td15.appendText(" (default), a number of pixels, or a CSS size like ");
  td15.createEl('code', { cls: 'vaultquery-help-code', text: "70vh" });
  const row14 = tbody1.createEl('tr');
  const td16 = row14.createEl('td');
  td16.createEl('code', { cls: 'vaultquery-help-code', text: "contentHeight" });
  row14.createEl('td', { text: "FullCalendar content area height, excluding the toolbar" });
  const row15 = tbody1.createEl('tr');
  const td17 = row15.createEl('td');
  td17.createEl('code', { cls: 'vaultquery-help-code', text: "aspectRatio" });
  row15.createEl('td', { text: "Width-to-height ratio used by FullCalendar when height is not fixed" });
  const row16 = tbody1.createEl('tr');
  const td18 = row16.createEl('td');
  td18.createEl('code', { cls: 'vaultquery-help-code', text: "expandRows" });
  const td19 = row16.createEl('td');
  td19.appendText("FullCalendar row expansion: ");
  td19.createEl('code', { cls: 'vaultquery-help-code', text: "true" });
  td19.appendText(" or ");
  td19.createEl('code', { cls: 'vaultquery-help-code', text: "false" });
  const row17 = tbody1.createEl('tr');
  const td20 = row17.createEl('td');
  td20.createEl('code', { cls: 'vaultquery-help-code', text: "firstDay" });
  const td21 = row17.createEl('td');
  td21.appendText("FullCalendar week start day: ");
  td21.createEl('code', { cls: 'vaultquery-help-code', text: "0" });
  td21.appendText(" = Sunday (default) through ");
  td21.createEl('code', { cls: 'vaultquery-help-code', text: "6" });
  td21.appendText(" = Saturday");
  const row18 = tbody1.createEl('tr');
  const td22 = row18.createEl('td');
  td22.createEl('code', { cls: 'vaultquery-help-code', text: "weekNumbers" });
  const td23 = row18.createEl('td');
  td23.appendText("FullCalendar week number display: ");
  td23.createEl('code', { cls: 'vaultquery-help-code', text: "true" });
  td23.appendText(" or ");
  td23.createEl('code', { cls: 'vaultquery-help-code', text: "false" });
  const row19 = tbody1.createEl('tr');
  const td24 = row19.createEl('td');
  td24.createEl('code', { cls: 'vaultquery-help-code', text: "visibleWeeks" });
  const td25 = row19.createEl('td');
  td25.appendText("Number of week rows shown by the Month toolbar button. Use ");
  td25.createEl('code', { cls: 'vaultquery-help-code', text: "1" });
  td25.appendText(" through ");
  td25.createEl('code', { cls: 'vaultquery-help-code', text: "6" });
  td25.appendText("; omitted means the normal FullCalendar month range");
  const row20 = tbody1.createEl('tr');
  const td26 = row20.createEl('td');
  td26.createEl('code', { cls: 'vaultquery-help-code', text: "mobileVisibleDays" });
  const td27 = row20.createEl('td');
  td27.appendText("On narrow screens, target this many visible day columns at once and page Month/Week forward by that many days. Use ");
  td27.createEl('code', { cls: 'vaultquery-help-code', text: "1" });
  td27.appendText(" through ");
  td27.createEl('code', { cls: 'vaultquery-help-code', text: "7" });
  const row21 = tbody1.createEl('tr');
  const td28 = row21.createEl('td');
  td28.createEl('code', { cls: 'vaultquery-help-code', text: "skipBlankPeriods" });
  const td29 = row21.createEl('td');
  td29.appendText("Replace toolbar previous/next navigation with jumps to the nearest earlier or later period that contains events. Defaults to ");
  td29.createEl('code', { cls: 'vaultquery-help-code', text: "false" });
  const row22 = tbody1.createEl('tr');
  const td30 = row22.createEl('td');
  td30.createEl('code', { cls: 'vaultquery-help-code', text: "dayMaxEvents" });
  const td31 = row22.createEl('td');
  td31.appendText("FullCalendar maximum events to show in month cells before overflow. Use a number or ");
  td31.createEl('code', { cls: 'vaultquery-help-code', text: "true" });
  const row23 = tbody1.createEl('tr');
  const td32 = row23.createEl('td');
  td32.createEl('code', { cls: 'vaultquery-help-code', text: "dayMaxEventRows" });
  const td33 = row23.createEl('td');
  td33.appendText("FullCalendar maximum event rows in day grid cells. Use a number or ");
  td33.createEl('code', { cls: 'vaultquery-help-code', text: "true" });
  const row24 = tbody1.createEl('tr');
  const td34 = row24.createEl('td');
  td34.createEl('code', { cls: 'vaultquery-help-code', text: "dayMinHeight" });
  row24.createEl('td', { text: "VaultQuery month day-cell minimum height in pixels" });
  const row25 = tbody1.createEl('tr');
  const td35 = row25.createEl('td');
  td35.createEl('code', { cls: 'vaultquery-help-code', text: "eventMaxStack" });
  row25.createEl('td', { text: "FullCalendar maximum stacked events in time grid views" });
  const row26 = tbody1.createEl('tr');
  const td36 = row26.createEl('td');
  td36.createEl('code', { cls: 'vaultquery-help-code', text: "slotMinTime" });
  const td37 = row26.createEl('td');
  td37.appendText("Earliest visible time in week/day views, e.g. ");
  td37.createEl('code', { cls: 'vaultquery-help-code', text: "08:00:00" });
  const row27 = tbody1.createEl('tr');
  const td38 = row27.createEl('td');
  td38.createEl('code', { cls: 'vaultquery-help-code', text: "slotMaxTime" });
  const td39 = row27.createEl('td');
  td39.appendText("Latest visible time in week/day views, e.g. ");
  td39.createEl('code', { cls: 'vaultquery-help-code', text: "18:00:00" });
  const row28 = tbody1.createEl('tr');
  const td40 = row28.createEl('td');
  td40.createEl('code', { cls: 'vaultquery-help-code', text: "slotDuration" });
  const td41 = row28.createEl('td');
  td41.appendText("Time slot interval in week/day views, e.g. ");
  td41.createEl('code', { cls: 'vaultquery-help-code', text: "00:30:00" });
  const para4 = container.createEl('p', { cls: 'vaultquery-help-paragraph' });
  para4.appendText("On narrow screens, the Month button stays available. Use ");
  para4.createEl('code', { cls: 'vaultquery-help-code', text: "mobileVisibleDays" });
  para4.appendText(" with ");
  para4.createEl('code', { cls: 'vaultquery-help-code', text: "visibleWeeks" });
  para4.appendText(" to create a horizontally scrollable compact grid. For example, ");
  para4.createEl('code', { cls: 'vaultquery-help-code', text: "mobileVisibleDays: 3" });
  para4.appendText(" and ");
  para4.createEl('code', { cls: 'vaultquery-help-code', text: "visibleWeeks: 3" });
  para4.appendText(" gives an approximately 3-by-3 viewport on portrait phones, and the Month/Week prev/next paging advances by 3 days at a time.");
  const para5 = container.createEl('p', { cls: 'vaultquery-help-paragraph' });
  para5.appendText("If the result set only contains all-day events, the Week and Day toolbar buttons switch to day-grid views so the hour axis does not waste space. If any event has a time component, Week and Day use FullCalendar time-grid views.");
  const para6 = container.createEl('p', { cls: 'vaultquery-help-paragraph' });
  para6.appendText("Events are clickable when the query returns a ");
  para6.createEl('code', { cls: 'vaultquery-help-code', text: "path" });
  para6.appendText(" column. Alias the note path column to ");
  para6.createEl('code', { cls: 'vaultquery-help-code', text: "path" });
  para6.appendText(" when needed. If no path column is returned, the event still renders and still has a tooltip, but clicking it does not open a note. Tooltips use a VaultQuery tooltip instead of the browser's native tooltip and include the event title, date range when present, and description when present.");
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Basic calendar" });
  const codeBlock = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-calendar\n" });
  const codeBlockCode = codeBlock.createEl('code');
  if (typeof Prism !== 'undefined' && Prism.languages["vaultquery-calendar"]) {
    codeBlockCode.innerHTML = Prism.highlight("SELECT\n  due_date as date,\n  task_text as title,\n  path\nFROM tasks\nWHERE due_date IS NOT NULL\nORDER BY due_date;", Prism.languages["vaultquery-calendar"], "vaultquery-calendar");
  } else {
    codeBlockCode.textContent = "SELECT\n  due_date as date,\n  task_text as title,\n  path\nFROM tasks\nWHERE due_date IS NOT NULL\nORDER BY due_date;";
  }
  codeBlock.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Weekly calendar" });
  const codeBlock1 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock1.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-calendar\n" });
  const codeBlock1Code = codeBlock1.createEl('code');
  if (typeof Prism !== 'undefined' && Prism.languages["vaultquery-calendar"]) {
    codeBlock1Code.innerHTML = Prism.highlight("SELECT\n  due_date as date,\n  task_text as title,\n  path,\n  status as description\nFROM tasks\nWHERE due_date IS NOT NULL\nORDER BY due_date;\n\nconfig:\ninitialView: timeGridWeek\ninitialDate: 2026-04-20\nfirstDay: 0", Prism.languages["vaultquery-calendar"], "vaultquery-calendar");
  } else {
    codeBlock1Code.textContent = "SELECT\n  due_date as date,\n  task_text as title,\n  path,\n  status as description\nFROM tasks\nWHERE due_date IS NOT NULL\nORDER BY due_date;\n\nconfig:\ninitialView: timeGridWeek\ninitialDate: 2026-04-20\nfirstDay: 0";
  }
  codeBlock1.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Daily calendar" });
  const codeBlock2 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock2.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-calendar\n" });
  const codeBlock2Code = codeBlock2.createEl('code');
  if (typeof Prism !== 'undefined' && Prism.languages["vaultquery-calendar"]) {
    codeBlock2Code.innerHTML = Prism.highlight("SELECT\n  due_date as date,\n  task_text as title,\n  path,\n  status as description\nFROM tasks\nWHERE due_date IS NOT NULL\nORDER BY due_date;\n\nconfig:\ninitialView: timeGridDay\ninitialDate: 2026-04-21", Prism.languages["vaultquery-calendar"], "vaultquery-calendar");
  } else {
    codeBlock2Code.textContent = "SELECT\n  due_date as date,\n  task_text as title,\n  path,\n  status as description\nFROM tasks\nWHERE due_date IS NOT NULL\nORDER BY due_date;\n\nconfig:\ninitialView: timeGridDay\ninitialDate: 2026-04-21";
  }
  codeBlock2.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Calendar with colors and descriptions" });
  const codeBlock3 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock3.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-calendar\n" });
  const codeBlock3Code = codeBlock3.createEl('code');
  if (typeof Prism !== 'undefined' && Prism.languages["vaultquery-calendar"]) {
    codeBlock3Code.innerHTML = Prism.highlight("SELECT\n  due_date as date,\n  done_date as end_date,\n  task_text as title,\n  path,\n  status as description,\n  CASE\n    WHEN status = 'DONE' THEN '#22c55e'\n    WHEN priority = 'high' THEN '#ef4444'\n    ELSE '#3b82f6'\n  END as backgroundColor,\n  CASE\n    WHEN priority = 'high' THEN '#ffffff'\n    WHEN status = 'DONE' THEN '#052e16'\n    ELSE '#ffffff'\n  END as color\nFROM tasks\nWHERE due_date IS NOT NULL\nORDER BY due_date;\n\nconfig:\nweekNumbers: true", Prism.languages["vaultquery-calendar"], "vaultquery-calendar");
  } else {
    codeBlock3Code.textContent = "SELECT\n  due_date as date,\n  done_date as end_date,\n  task_text as title,\n  path,\n  status as description,\n  CASE\n    WHEN status = 'DONE' THEN '#22c55e'\n    WHEN priority = 'high' THEN '#ef4444'\n    ELSE '#3b82f6'\n  END as backgroundColor,\n  CASE\n    WHEN priority = 'high' THEN '#ffffff'\n    WHEN status = 'DONE' THEN '#052e16'\n    ELSE '#ffffff'\n  END as color\nFROM tasks\nWHERE due_date IS NOT NULL\nORDER BY due_date;\n\nconfig:\nweekNumbers: true";
  }
  codeBlock3.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Calendar events without note links" });
  const codeBlock4 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock4.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-calendar\n" });
  const codeBlock4Code = codeBlock4.createEl('code');
  if (typeof Prism !== 'undefined' && Prism.languages["vaultquery-calendar"]) {
    codeBlock4Code.innerHTML = Prism.highlight("WITH events(date, title, description, backgroundColor, color) AS (\n  VALUES\n    ('2026-04-20', 'Planning meeting', 'Generated by SQL; not linked to a note', '#3b82f6', '#ffffff'),\n    ('2026-04-21', 'Follow-up', 'Hover shows this tooltip, click does not open a note', '#22c55e', '#052e16')\n)\nSELECT date, title, description, backgroundColor, color\nFROM events\nORDER BY date;\n\nconfig:\ninitialView: dayGridMonth\ninitialDate: 2026-04-01", Prism.languages["vaultquery-calendar"], "vaultquery-calendar");
  } else {
    codeBlock4Code.textContent = "WITH events(date, title, description, backgroundColor, color) AS (\n  VALUES\n    ('2026-04-20', 'Planning meeting', 'Generated by SQL; not linked to a note', '#3b82f6', '#ffffff'),\n    ('2026-04-21', 'Follow-up', 'Hover shows this tooltip, click does not open a note', '#22c55e', '#052e16')\n)\nSELECT date, title, description, backgroundColor, color\nFROM events\nORDER BY date;\n\nconfig:\ninitialView: dayGridMonth\ninitialDate: 2026-04-01";
  }
  codeBlock4.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
}