// Generated by md-to-obsidian-dom
// Source: vaultquery-chart-help.md

import './styles.generated.css';

import type { RenderContext } from './types.generated';

export const pageId = "vaultquery-chart-help";
export const pageTitle = "VaultQuery Chart Help";

export const meta = {
  id: "vaultquery-chart-help",
  title: "VaultQuery Chart Help",
};

export const dynamicKeys: string[] = [];
export const linkedPages: string[] = [];

/**
 * Render the "VaultQuery Chart Help" help page
 * @param container - Container element to render into
 * @param _ctx - Render context with code highlighting and dynamic content handlers
 */
export function render(container: HTMLElement, _ctx: RenderContext): void {
  container.createEl('h1', { cls: 'vaultquery-help-heading vaultquery-help-h1', text: "Charts & visualizations" });
  const para = container.createEl('p', { cls: 'vaultquery-help-paragraph' });
  para.appendText("Use ");
  para.createEl('code', { cls: 'vaultquery-help-code', text: "vaultquery-chart" });
  para.appendText(" to render query results as charts. Query must use ");
  para.createEl('code', { cls: 'vaultquery-help-code', text: "label" });
  para.appendText(" and ");
  para.createEl('code', { cls: 'vaultquery-help-code', text: "value" });
  para.appendText(" columns (or ");
  para.createEl('code', { cls: 'vaultquery-help-code', text: "x" });
  para.appendText("/");
  para.createEl('code', { cls: 'vaultquery-help-code', text: "y" });
  para.appendText(" for scatter). Add a ");
  para.createEl('code', { cls: 'vaultquery-help-code', text: "series" });
  para.appendText(" column for multiple datasets.");
  const para1 = container.createEl('p', { cls: 'vaultquery-help-paragraph' });
  para1.appendText("Chart output uses ");
  para1.createEl('a', { cls: 'vaultquery-help-link vaultquery-help-external-link', text: "Chart.js", attr: { href: "https://www.chartjs.org/", target: '_blank', rel: 'noopener' } });
  para1.appendText(".");
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Chart result columns" });
  const tableWrapper = container.createDiv({ cls: 'vaultquery-help-table-wrapper' });
  const table = tableWrapper.createEl('table', { cls: 'vaultquery-help-table' });
  const thead = table.createEl('thead');
  const row = thead.createEl('tr');
  row.createEl('th', { text: "Column" });
  row.createEl('th', { text: "Description" });
  const tbody = table.createEl('tbody');
  const row1 = tbody.createEl('tr');
  const td = row1.createEl('td');
  td.createEl('code', { cls: 'vaultquery-help-code', text: "label" });
  row1.createEl('td', { text: "X/category label for bar, line, pie, and doughnut charts" });
  const row2 = tbody.createEl('tr');
  const td1 = row2.createEl('td');
  td1.createEl('code', { cls: 'vaultquery-help-code', text: "value" });
  row2.createEl('td', { text: "Numeric value for bar, line, pie, and doughnut charts" });
  const row3 = tbody.createEl('tr');
  const td2 = row3.createEl('td');
  td2.createEl('code', { cls: 'vaultquery-help-code', text: "x" });
  row3.createEl('td', { text: "X value for scatter charts" });
  const row4 = tbody.createEl('tr');
  const td3 = row4.createEl('td');
  td3.createEl('code', { cls: 'vaultquery-help-code', text: "y" });
  row4.createEl('td', { text: "Y value for scatter charts" });
  const row5 = tbody.createEl('tr');
  const td4 = row5.createEl('td');
  td4.createEl('code', { cls: 'vaultquery-help-code', text: "series" });
  row5.createEl('td', { text: "Optional dataset/group name for multiple datasets" });
  const row6 = tbody.createEl('tr');
  const td5 = row6.createEl('td');
  td5.createEl('code', { cls: 'vaultquery-help-code', text: "chartType" });
  row6.createEl('td', { text: "Optional per-series chart type for mixed charts" });
  const row7 = tbody.createEl('tr');
  const td6 = row7.createEl('td');
  td6.createEl('code', { cls: 'vaultquery-help-code', text: "backgroundColor" });
  row7.createEl('td', { text: "Optional color for a point, bar, slice, or dataset item" });
  const row8 = tbody.createEl('tr');
  const td7 = row8.createEl('td');
  td7.createEl('code', { cls: 'vaultquery-help-code', text: "borderColor" });
  row8.createEl('td', { text: "Optional border/line color" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Chart config options" });
  const tableWrapper1 = container.createDiv({ cls: 'vaultquery-help-table-wrapper' });
  const table1 = tableWrapper1.createEl('table', { cls: 'vaultquery-help-table' });
  const thead1 = table1.createEl('thead');
  const row9 = thead1.createEl('tr');
  row9.createEl('th', { text: "Option" });
  row9.createEl('th', { text: "Description" });
  const tbody1 = table1.createEl('tbody');
  const row10 = tbody1.createEl('tr');
  const td8 = row10.createEl('td');
  td8.createEl('code', { cls: 'vaultquery-help-code', text: "type" });
  const td9 = row10.createEl('td');
  td9.createEl('code', { cls: 'vaultquery-help-code', text: "bar" });
  td9.appendText(", ");
  td9.createEl('code', { cls: 'vaultquery-help-code', text: "line" });
  td9.appendText(", ");
  td9.createEl('code', { cls: 'vaultquery-help-code', text: "pie" });
  td9.appendText(", ");
  td9.createEl('code', { cls: 'vaultquery-help-code', text: "doughnut" });
  td9.appendText(", or ");
  td9.createEl('code', { cls: 'vaultquery-help-code', text: "scatter" });
  td9.appendText(" (required)");
  const row11 = tbody1.createEl('tr');
  const td10 = row11.createEl('td');
  td10.createEl('code', { cls: 'vaultquery-help-code', text: "title" });
  row11.createEl('td', { text: "Chart title" });
  const row12 = tbody1.createEl('tr');
  const td11 = row12.createEl('td');
  td11.createEl('code', { cls: 'vaultquery-help-code', text: "datasetLabel" });
  row12.createEl('td', { text: "Legend label for the dataset" });
  const row13 = tbody1.createEl('tr');
  const td12 = row13.createEl('td');
  td12.createEl('code', { cls: 'vaultquery-help-code', text: "xLabel" });
  row13.createEl('td', { text: "X-axis label for bar, line, and scatter charts" });
  const row14 = tbody1.createEl('tr');
  const td13 = row14.createEl('td');
  td13.createEl('code', { cls: 'vaultquery-help-code', text: "yLabel" });
  row14.createEl('td', { text: "Y-axis label for bar, line, and scatter charts" });
  const row15 = tbody1.createEl('tr');
  const td14 = row15.createEl('td');
  td14.createEl('code', { cls: 'vaultquery-help-code', text: "datasetBackgroundColor" });
  const td15 = row15.createEl('td');
  td15.appendText("Dataset fill color, e.g. ");
  td15.createEl('code', { cls: 'vaultquery-help-code', text: "rgba(54, 162, 235, 0.8)" });
  const row16 = tbody1.createEl('tr');
  const td16 = row16.createEl('td');
  td16.createEl('code', { cls: 'vaultquery-help-code', text: "datasetBorderColor" });
  row16.createEl('td', { text: "Dataset border/line color" });
  const para2 = container.createEl('p', { cls: 'vaultquery-help-paragraph' });
  para2.appendText("Use result columns for per-row or per-series colors when colors should come from SQL. Use config colors when one dataset-level color is enough.");
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Bar chart" });
  const codeBlock = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-chart\n" });
  const code = codeBlock.createEl('code');
  renderPrismCode(code, "SELECT tag_name as label, COUNT(*) as value\nFROM tags\nGROUP BY tag_name\nORDER BY value DESC\nLIMIT 10;\n\nconfig:\ntype: bar\ndatasetLabel: Tag count", "vaultquery-chart");
  codeBlock.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Bar chart with custom color" });
  const codeBlock1 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock1.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-chart\n" });
  const code1 = codeBlock1.createEl('code');
  renderPrismCode(code1, "SELECT tag_name as label, COUNT(*) as value\nFROM tags\nGROUP BY tag_name\nLIMIT 5;\n\nconfig:\ntype: bar\ndatasetBackgroundColor: rgba(75, 192, 192, 0.8)\ndatasetBorderColor: rgba(75, 192, 192, 1)", "vaultquery-chart");
  codeBlock1.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Per-bar colors via SQL" });
  const para3 = container.createEl('p', { cls: 'vaultquery-help-paragraph' });
  para3.appendText("Use a ");
  para3.createEl('code', { cls: 'vaultquery-help-code', text: "backgroundColor" });
  para3.appendText(" column to set colors per data point:");
  const codeBlock2 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock2.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-chart\n" });
  const code2 = codeBlock2.createEl('code');
  renderPrismCode(code2, "SELECT\n  tag_name as label,\n  COUNT(*) as value,\n  CASE\n    WHEN tag_name = '#important' THEN 'rgba(255, 99, 132, 0.8)'\n    ELSE 'rgba(54, 162, 235, 0.8)'\n  END as backgroundColor\nFROM tags\nGROUP BY tag_name\nLIMIT 5;\n\nconfig:\ntype: bar", "vaultquery-chart");
  codeBlock2.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Multi-series bar chart" });
  const codeBlock3 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock3.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-chart\n" });
  const code3 = codeBlock3.createEl('code');
  renderPrismCode(code3, "SELECT status as label, priority as series, COUNT(*) as value\nFROM tasks\nGROUP BY status, priority;\n\nconfig:\ntype: bar\ntitle: Tasks by status and priority", "vaultquery-chart");
  codeBlock3.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Mixed chart" });
  const para4 = container.createEl('p', { cls: 'vaultquery-help-paragraph' });
  para4.appendText("Use a ");
  para4.createEl('code', { cls: 'vaultquery-help-code', text: "chartType" });
  para4.appendText(" column to mix chart types:");
  const codeBlock4 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock4.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-chart\n" });
  const code4 = codeBlock4.createEl('code');
  renderPrismCode(code4, "SELECT label, value, series, chartType, backgroundColor FROM (\n  SELECT 'Jan' as label, 10 as value, 'Sales' as series,\n         'bar' as chartType, 'rgba(54, 162, 235, 0.8)' as backgroundColor\n  UNION ALL\n  SELECT 'Jan', 8, 'Trend', 'line', 'rgba(255, 99, 132, 1)'\n  UNION ALL\n  SELECT 'Feb', 15, 'Sales', 'bar', 'rgba(54, 162, 235, 0.8)'\n  UNION ALL\n  SELECT 'Feb', 12, 'Trend', 'line', 'rgba(255, 99, 132, 1)'\n);\n\nconfig:\ntype: bar\ntitle: Sales vs Trend", "vaultquery-chart");
  codeBlock4.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Line chart with axis labels" });
  const codeBlock5 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock5.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-chart\n" });
  const code5 = codeBlock5.createEl('code');
  renderPrismCode(code5, "SELECT done_date as label, COUNT(*) as value\nFROM tasks\nWHERE status = 'DONE'\nGROUP BY done_date\nORDER BY done_date;\n\nconfig:\ntype: line\nxLabel: Date\nyLabel: Completed\ndatasetLabel: Tasks completed", "vaultquery-chart");
  codeBlock5.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
  container.createEl('h2', { cls: 'vaultquery-help-heading vaultquery-help-h2', text: "Scatter chart" });
  const codeBlock6 = container.createEl('pre', { cls: 'HyperMD-codeblock HyperMD-codeblock-bg display-only' });
  codeBlock6.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "```vaultquery-chart\n" });
  const code6 = codeBlock6.createEl('code');
  renderPrismCode(code6, "SELECT\n  size as x,\n  length(content) as y,\n  title as series\nFROM notes\nWHERE size IS NOT NULL\nORDER BY size DESC\nLIMIT 25;\n\nconfig:\ntype: scatter\nxLabel: File size\nyLabel: Content length", "vaultquery-chart");
  codeBlock6.createSpan({ cls: 'vaultquery-help-fence cm-formatting', text: "\n```" });
}

type PrismTokenStream = string | PrismToken | PrismTokenStream[];

interface PrismToken {
  type: string;
  content: PrismTokenStream;
  alias?: string | string[];
}

interface PrismApi {
  languages: Record<string, unknown>;
  tokenize: (code: string, grammar: unknown) => PrismTokenStream[];
}

declare const Prism: PrismApi | undefined;

function renderPrismCode(container: HTMLElement, source: string, language: string): void {
  const prism = typeof Prism !== 'undefined' ? Prism : undefined;
  const grammar = prism?.languages[language];

  if (!prism || !grammar) {
    container.appendText(source);
    return;
  }

  appendPrismTokens(container, prism.tokenize(source, grammar));
}

function appendPrismTokens(container: HTMLElement, tokenStream: PrismTokenStream): void {
  if (typeof tokenStream === 'string') {
    container.appendText(tokenStream);
    return;
  }

  if (Array.isArray(tokenStream)) {
    for (const token of tokenStream) {
      appendPrismTokens(container, token);
    }
    return;
  }

  const aliases = Array.isArray(tokenStream.alias)
    ? tokenStream.alias
    : tokenStream.alias ? [tokenStream.alias] : [];
  const span = container.createSpan({ cls: ['token', tokenStream.type, ...aliases].join(' ') });
  appendPrismTokens(span, tokenStream.content);
}