import { writeFileSync } from 'node:fs';

// `api.d.ts` is bundled from src/api.ts by rollup.dts.mjs into a single
// self-contained declaration file. This writes the root entry point, which
// only forwards to it.
const indexDeclaration = `/**
 * VaultQuery public API types for third-party plugin integration.
 * GENERATED by scripts/generate-api-dts.mjs (npm run generate) - do not edit.
 *
 * Usage:
 *   npm install --save-dev github:bobstanton/vaultquery
 *
 *   import type { IVaultQueryAPI, QueryResult, PreviewResult } from 'vaultquery/api';
 */

export * from './api';
`;

writeFileSync('index.d.ts', indexDeclaration);
