import { readFileSync, writeFileSync } from 'node:fs';

// api.d.ts (the `vaultquery/api` entry point) is src/api.ts with its relative
// imports rewritten to resolve from the repository root.
const source = readFileSync('src/api.ts', 'utf8');

const declaration = source
  .replace(/from '\.\//g, "from './src/")
  .replace(/import\('\.\//g, "import('./src/");

writeFileSync('api.d.ts', declaration);

const indexDeclaration = `/**
 * VaultQuery public API types for third-party plugin integration.
 * GENERATED by scripts/generate-api-dts.mjs (npm run generate) - do not edit.
 *
 * Usage:
 *   npm install --save-dev github:bobstanton/vaultquery
 *
 *   import type { IVaultQueryAPI, QueryResult, PreviewResult } from 'vaultquery/api';
 */

export * from './api';
`;

writeFileSync('index.d.ts', indexDeclaration);
